# Generated by Django 2.2 on 2019-04-23 15:47

from django.db import migrations


def populate_payment_source_type(apps, schema_editor):
    PaymentSourceType = apps.get_model('dashboard', 'PaymentSourceType')
    PaymentSourceType(handle='BANK_ACCOUNT', description='Bank account').save()
    PaymentSourceType(handle='DEBIT_CARD', description='Debit Card').save()
    PaymentSourceType(handle='CREDIT_CARD', description='Credit Card').save()


def empty_payment_source_type(apps, schema_editor):
    PaymentSourceType = apps.get_model('dashboard', 'PaymentSourceType')
    PaymentSourceType.objects.filter(handle='BANK_ACCOUNT').delete()
    PaymentSourceType.objects.filter(handle='DEBIT_CARD').delete()
    PaymentSourceType.objects.filter(handle='CREDIT_CARD').delete()


def populate_expense_frequency(apps, schema_editor):
    ExpenseFrequency = apps.get_model('dashboard', 'ExpenseFrequency')
    ExpenseFrequency(handle='ONE_TIME', description='One time expense').save()
    ExpenseFrequency(handle='MONTHLY', description='Monthly expense').save()
    ExpenseFrequency(handle='YEARLY', description='Yearly expense').save()


def empty_expense_frequency(apps, schema_editor):
    ExpenseFrequency = apps.get_model('dashboard', 'ExpenseFrequency')
    ExpenseFrequency.objects.filter(handle='ONE_TIME').delete()
    ExpenseFrequency.objects.filter(handle='MONTHLY').delete()
    ExpenseFrequency.objects.filter(handle='YEARLY').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_payment_source_type, reverse_code=empty_payment_source_type),
        migrations.RunPython(populate_expense_frequency, reverse_code=empty_expense_frequency),
    ]
